### PR TITLE
Implement ExecuteSQLOp.to_diff_tuple, fixes #1335

### LINKED ISSUE #1335: check does not work with ExecuteSQLOp present
### Discussed in https://github.com/sqlalchemy/alembic/discussions/1334

<div type='discussions-op-text'>

<sup>Originally posted by **BayerSe** October 23, 2023</sup>
Hi,

we're using `ExecuteSQLOp` to add triggers to some columns. 

With these added, `alembic check` nowadays raises a not implemented error, it seems as if because `ExecuteSQLOp` does not implement `.to_diff_tuple()`.

```python
op = ops.ExecuteSQLOp(sqltext='CREATE OR REPLACE TRIGGER ...')
op.to_diff_tuple()  # NotImplementedError
```

This used to work in version `1.6.5` and I think this error was introduced in  `1.7.0` when `.to_diff_tuple()` was added to the base class `MigrateOperation`, see [here](https://github.com/sqlalchemy/alembic/blob/rel_1_7_0/alembic/operations/ops.py#L82).

Here's the stacktrace of `alembic check`:

```sh
INFO  [alembic.runtime.migration] Context impl OracleImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.autogenerate.compare] Detected added table 'his_test'
Traceback (most recent call last):
  File "/home/user/PycharmProjects/project/.venv/bin/alembic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/PycharmProjects/project/.venv/lib/python3.11/site-packages/alembic/config.py", line 630, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/user/PycharmProjects/project/.venv/lib/python3.11/site-packages/alembic/config.py", line 624, in main
    self.run_cmd(cfg, options)
  File "/home/user/PycharmProjects/project/.venv/lib/python3.11/site-packages/alembic/config.py", line 601, in run_cmd
    fn(
  File "/home/user/PycharmProjects/project/.venv/lib/python3.11/site-packages/alembic/command.py", line 294, in check
    diffs = migration_script.upgrade_ops.as_diffs()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/PycharmProjects/project/.venv/lib/python3.11/site-packages/alembic/operations/ops.py", line 2556, in as_diffs
    return list(OpContainer._ops_as_diffs(self))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/PycharmProjects/project/.venv/lib/python3.11/site-packages/alembic/operations/ops.py", line 2566, in _ops_as_diffs
    yield op.to_diff_tuple()
          ^^^^^^^^^^^^^^^^^^
  File "/home/user/PycharmProjects/project/.venv/lib/python3.11/site-packages/alembic/operations/ops.py", line 88, in to_diff_tuple
    raise NotImplementedError
NotImplementedError
```

I have no idea how this worked in 1.6.5 as already there, `ExecuteSQLOp` and some other ops did not have `.to_diff_tuple()`, but with `.to_diff_tuple()` in the base class `check` does not work as of today.

Thanks
Sebastian

</div>

### PR DESCRIPTION
**Pull request by BayerSe**
### Description
This implements ExecuteSQLOp.to_diff_tuple, which is necessary when custom SQL statements are added to the diff stream via some hook.

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 4ec6638bc28d048da5745e854e584fb3581af9c2 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 4ec6638bc28d048da5745e854e584fb3581af9c2: https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4914

**Comment by zzzeek** [comment]
great, looks like you filled out the whole format/changelog, thanks

**Comment by zzzeek** [comment]
this is currently failing CI for a few small reasons - are you able to check out the failures for SQLA 1.3 and pep8 over at https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4914 on the left side?

**Comment by BayerSe** [comment]
@zzzeek should be fixed now, can you please trigger another CI run?

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision c5e217e99d0fae87ccc89fc57c71e1c07c57ea97 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Patchset c5e217e99d0fae87ccc89fc57c71e1c07c57ea97 added to existing Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4914

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4914 has been **merged**. Congratulations! :)
