### ISSUE TITLE
Script to generate pyi failes fails on Python 3.8

### ISSUE THREAD

**Issue by TilmanK** [sqlalchemy/alembic#915]
**Describe the bug**
The script `write_pyi.py` fails when running it with Python 3.8, but succeeds on Python 3.9.

**Expected behavior**
Runs on both or fails explicitly with some clear statement that it can't be run on 3.9

**To Reproduce**
Running it on Python 3.8 fails when running this function call:
```py
    console_scripts(
        str(destination_path),
        {"entrypoint": "zimports", "options": "-e"},
        ignore_output=ignore_output,
    )
```

This happens, because the code assumes (write_hooks.py:141), that the returned object `EntryPoint` has a `module` or `attr` property (which it has on 3.9, but not on 3.8).
```py
        [
            sys.executable,
            "-c",
            "import %s; %s.%s()" % (impl.module, impl.module, impl.attr),
        ]
```

The difference between the two versions are the different imports in compat.py:32:
```py
if py38:
    from importlib import metadata as importlib_metadata
else:
    import importlib_metadata  # type:ignore[no-redef] # noqa
```
**Error**
```
C:\Users\krumm-ti\Documents\PycharmProjects\alembic\venv\Scripts\python.exe C:/Users/krumm-ti/Documents/PycharmProjects/alembic/tools/write_pyi.py
Traceback (most recent call last):
  File "C:/Users/krumm-ti/Documents/PycharmProjects/alembic/tools/write_pyi.py", line 199, in <module>
    main(args)
  File "C:/Users/krumm-ti/Documents/PycharmProjects/alembic/tools/write_pyi.py", line 173, in main
    run_file(
  File "C:/Users/krumm-ti/Documents/PycharmProjects/alembic/tools/write_pyi.py", line 146, in run_file
    generate_pyi_for_proxy(
  File "C:/Users/krumm-ti/Documents/PycharmProjects/alembic/tools/write_pyi.py", line 75, in generate_pyi_for_proxy
    console_scripts(
  File "C:\Users\krumm-ti\Documents\PycharmProjects\alembic\venv\lib\site-packages\alembic\script\write_hooks.py", line 145, in console_scripts
    "import %s; %s.%s()" % (impl.module, impl.module, impl.attr),
AttributeError: 'EntryPoint' object has no attribute 'module'
```

**Versions.**
 - OS: Windows 10
 - Python: 3.8/3.9
 - Alembic: current master
 - SQLAlchemy:
 - Database:
 - DBAPI:

**Additional context**

**Have a nice day!**

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting, since this is a development only script, I think we could just have it error if it's executed with python < 3.9.
It's not included in the published bundle, so it should not impact any alembic usage

**Comment by TilmanK** [comment]
That's what I thought. I'll send a PR.

**Comment by CaselIT** [comment]
thanks!

**Comment by sqla-tester** [comment]
**TilmanK** has proposed a fix for this issue in the **master** branch:

**Adds exception when trying to run write_pyi.py with Python < 3.9** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/3080

**Comment by antoni-szych-rtbhouse** [comment]
Hi, I have an issue which boils down to the same point in alembic code, but I'm not using any development-only script, but `[post_write_hooks]` feature.

Relevant part of alembic.ini:
```
[post_write_hooks]

# format using "black" - use the console_scripts runner, against the "black" entrypoint
hooks = black, isort
black.type = console_scripts
black.entrypoint = black
black.options = REVISION_SCRIPT_FILENAME

isort.type = console_scripts
isort.entrypoint = isort
isort.options = REVISION_SCRIPT_FILENAME
```

```
16:18 $ poetry run alembic revision --autogenerate -m "Add foobar"
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
  Generating /home/foobar/myproject/api/migrations/versions/2021_09_27_6c36df7b6df9_add_foobar.py ...  done
  Running post write hook "black" ...
  FAILED
Traceback (most recent call last):
  File "/home/foobar/.cache/pypoetry/virtualenvs/someenv-py3.8/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/home/foobar/.cache/pypoetry/virtualenvs/someenv-py3.8/lib/python3.8/site-packages/alembic/config.py", line 588, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/foobar/.cache/pypoetry/virtualenvs/someenv-py3.8/lib/python3.8/site-packages/alembic/config.py", line 582, in main
    self.run_cmd(cfg, options)
  File "/home/foobar/.cache/pypoetry/virtualenvs/someenv-py3.8/lib/python3.8/site-packages/alembic/config.py", line 559, in run_cmd
    fn(
  File "/home/foobar/.cache/pypoetry/virtualenvs/someenv-py3.8/lib/python3.8/site-packages/alembic/command.py", line 234, in revision
    scripts = [script for script in revision_context.generate_scripts()]
  File "/home/foobar/.cache/pypoetry/virtualenvs/someenv-py3.8/lib/python3.8/site-packages/alembic/command.py", line 234, in <listcomp>
    scripts = [script for script in revision_context.generate_scripts()]
  File "/home/foobar/.cache/pypoetry/virtualenvs/someenv-py3.8/lib/python3.8/site-packages/alembic/autogenerate/api.py", line 600, in generate_scripts
    yield self._to_script(generated_revision)
  File "/home/foobar/.cache/pypoetry/virtualenvs/someenv-py3.8/lib/python3.8/site-packages/alembic/autogenerate/api.py", line 505, in _to_script
    return self.script_directory.generate_revision(
  File "/home/foobar/.cache/pypoetry/virtualenvs/someenv-py3.8/lib/python3.8/site-packages/alembic/script/base.py", line 736, in generate_revision
    write_hooks._run_hooks(path, post_write_hooks)
  File "/home/foobar/.cache/pypoetry/virtualenvs/someenv-py3.8/lib/python3.8/site-packages/alembic/script/write_hooks.py", line 84, in _run_hooks
    util.status(
  File "/home/foobar/.cache/pypoetry/virtualenvs/someenv-py3.8/lib/python3.8/site-packages/alembic/util/messaging.py", line 56, in status
    ret = fn(*arg, **kw)
  File "/home/foobar/.cache/pypoetry/virtualenvs/someenv-py3.8/lib/python3.8/site-packages/alembic/script/write_hooks.py", line 58, in _invoke
    return hook(revision, options)
  File "/home/foobar/.cache/pypoetry/virtualenvs/someenv-py3.8/lib/python3.8/site-packages/alembic/script/write_hooks.py", line 145, in console_scripts
    "import %s; %s.%s()" % (impl.module, impl.module, impl.attr),
AttributeError: 'EntryPoint' object has no attribute 'module'
```

The origin of the issue is of course the same, `alembic/script/write_hooks.py` seems to be working with python 3.9+ as discovered [above](https://github.com/sqlalchemy/alembic/issues/915#issue-994675520):
>This happens, because the code assumes (write_hooks.py:141), that the returned object EntryPoint has a module or attr property (which it has on 3.9, but not on 3.8).

While `write_pyi.py` is an script for development use only, I guess that all post-write hooks deal with the same issue as well?

**Comment by zzzeek** [comment]
that's a regression.  can you create a separate issue?

**Comment by zzzeek** [comment]
> Hi,
> 
> Thanks for reporting, since this is a development only script, I think we could just have it error if it's executed with python < 3.9.
> It's not included in the published bundle, so it should not impact any alembic usage

we should have just fixed it

**Comment by CaselIT** [comment]
> 
> 
> > Hi,
> > Thanks for reporting, since this is a development only script, I think we could just have it error if it's executed with python < 3.9.
> > It's not included in the published bundle, so it should not impact any alembic usage
> 
> we should have just fixed it

I though it was coming from `write_pyi.py` not from alembic api.

**Comment by CaselIT** [comment]
> 
> 
> that's a regression. can you create a separate issue?

I've added #934

**Comment by antoni-szych-rtbhouse** [comment]
>I've added #934

Thanks a lot!
