### PR TITLE
Fix type annotation for `url`

### PR DESCRIPTION
**Pull request by Viicos**
Left the `pyi` generated file untouched.
### Checklist

This pull request is:

- [x] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by CaselIT** [comment]
Thanks!

Let's see if the ci is happy with it

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision d15cb6e28d5bb934d139ced87e713a9d77505346 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by CaselIT** [comment]
@zzzeek the bot thingy seems broke

**Comment by zzzeek** [comment]
Ok its likely githubs change of their RSA key.  I'm out of town today so maybe late tonight or tomorrow I can look

**Comment by CaselIT** [comment]
That was my guess as well.

> so maybe late tonight or tomorrow I can look

sounds good, thanks!

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision d15cb6e28d5bb934d139ced87e713a9d77505346 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change d15cb6e28d5bb934d139ced87e713a9d77505346: https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4529

**Review by sqla-tester — COMMENTED** [review]
**mike bayer** (zzzeek) wrote:

the imports wont work in 1.4 even though they are only in TYPE_CHECKING, seems like we should not change them yet

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4529

* alembic/context.pyi (line 19): these have to be reverted to what they were previously as these imports aren't valid for SQLAlchemy 1.4, if someone is still on SQLA 1.4 this will degrade the quality of their typing experience:


  >>> import sqlalchemy
  >>> sqlalchemy.__version__
  '1.4.48'
  >>> from sqlalchemy import ClauseElement
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
  ImportError: cannot import name 'ClauseElement' from 'sqlalchemy' (/home/classic/dev/sqlalchemy/lib/sqlalchemy/__init__.py)
  >>> from sqlalchemy import URL
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
  ImportError: cannot import name 'URL' from 'sqlalchemy' (/home/classic/dev/sqlalchemy/lib/sqlalchemy/__init__.py)
  >>> from sqlalchemy import Connection
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
  ImportError: cannot import name 'Connection' from 'sqlalchemy' (/home/classic/dev/sqlalchemy/lib/sqlalchemy/__init__.py)
* alembic/context.pyi (line 79): this should be `Optional[Union[str, URL]]`
* tools/write_pyi.py (line 36): not sure this one can be trimmed yet as URL is not in sqlalchemy. in 1.4

**Review by sqla-tester — COMMENTED** [review]
**Federico Caselli** (CaselIT) wrote:

forgot about 1.4

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4529

* alembic/context.pyi (line 19): here's the reason for these imports! will fix

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

great thanks!

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4529

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4529 has been **merged**. Congratulations! :)
